import { getBrowser } from "./getBrowser.js";
import { getBrowserVersion } from "./getBrowserVersion.js";
import { getDate } from "./getDate.js";
import { getTime } from "./getDate.js";
import { getMilliseconds } from "./getDate.js";
import { getSeconds } from "./getDate.js";
import { getMinutes } from "./getDate.js";
import { getHours } from "./getDate.js";
import { getDay } from "./getDate.js";
import { getWeekDay } from "./getDate.js";
import { getWeek } from "./getDate.js";
import { getMonth } from "./getDate.js";
import { getYear } from "./getDate.js";
import { getDateFormatted } from "./getDate.js";
import { getOS } from "./getOS.js";
import { getOSVersion } from "./getOSVersion.js";
import { isMobile } from "./isMobile.js";
export { getBrowser, getBrowserVersion, getDate, getTime, getMilliseconds, getSeconds, getMinutes, getHours, getDay, getWeekDay, getWeek, getMonth, getYear, getDateFormatted, getOS, getOSVersion, isMobile };
